title: "Piyoshiのページ"
description: "フロントエンドとバックエンドからインフラまで頑張っていきたいエンジニア。マイクロサービスとかDDDとか自動テストとか推進していきたい。"
author: Satoshi Ueno
github_username: Piyoshi

lang: ja
timezone: Asia/Tokyo

#theme: jekyll-theme-architect
#theme: jekyll-theme-cayman
#theme: jekyll-theme-dinky
#theme: jekyll-theme-hacker
#theme: jekyll-theme-leap-day
#theme: jekyll-theme-merlot
#theme: jekyll-theme-midnight
#theme: jekyll-theme-minimal
#theme: jekyll-theme-modernist
theme: jekyll-theme-slate
#theme: jekyll-theme-tactile
#theme: jekyll-theme-time-machine

show_downloads: false

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "vendor/"
  - "docker-compose.yml"
